### ISSUE TITLE
The function "extract midsurface" in ParaView crashes when used.

### ISSUE THREAD

**Issue by 201434** [kaust-vislab/MidSurfer#1]
When I directly use the "extract midsurface (simple)" plugin on Fig7.vti and Fig13B.vti, Paraview crashes every time I try to display or export the resulting midsurface in Paraview. However, the plugin works normally on the smaller dataset Fig13A.vti. What could be the reason for this?As shown in the following figure, I am unable to display or export the file named "ExtractMidsurfacesimple2."
![1](https://github.com/user-attachments/assets/72db7868-73c4-47c7-9fde-86d43c090bf3)
Additionally, I would like to know if the "extract midsurface (simple)" plugin is only applicable to files in the VTI format?

**Comment by theusst** [comment]
it indeed crashed on Windows (Mac and Linux versions worked fine), it seems because Windows uses a rather small stack size and it simply ran out of memory

I have replaced the recursion in the computation of the connected components with a queue based approach, this seems to fix it

extracting a midsurface will work for all formats that store a segmentation mask and are read as 'Image (Uniform Rectilinear Grid)' (check Type in the Data Statistics section on the Information panel)
